extends:
  - airbnb-base
  - plugin:ava/recommended

parserOptions:
  ecmaVersion: 2019
  sourceType: module

env:
  node: true

plugins:
  - types
  - ava

rules:
  no-console: off
  types/assign-type: error
